# Generated by Django 3.0.6 on 2020-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_recipe_type_of_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.CharField(default=None, max_length=2083),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepare_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_of_meal',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('soup', 'Soup'), ('dessert', 'Dessert')], default='dinner', max_length=9),
        ),
    ]
